import AuthContextProvider from "@/context/AuthContext";
import "../styles/globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "@/components/ui/toaster"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="h-screen overflow-hidden">
        <Toaster></Toaster>
        <main className={`h-full overflow-hidden ${poppins.className}`}>
          <AuthContextProvider>{children}</AuthContextProvider>
        </main>
      </body>
    </html>
  );
}
